Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })
describe('test09', () => {
    it('Wybór koloru', () => {
        cy.visit('https://artmeb-hurt.pl/')
        cy.contains('Sklep').click()
        cy.contains("h5","Amor Velvet PIK").click()
        cy.get(':nth-child(1) > .offer-color > img').click()
        cy.get(':nth-child(2) > .offer-color > img').click()
        cy.get(':nth-child(3) > .offer-color > img').click()
        cy.get(':nth-child(4) > .offer-color > img').click()
        cy.get(':nth-child(5) > .offer-color > img').click()
        cy.get(':nth-child(6) > .offer-color > img').click()
        cy.get(':nth-child(7) > .offer-color > img').click()
        cy.get(':nth-child(8) > .offer-color > img').click()
        cy.get(':nth-child(9) > .offer-color > img').click()
        cy.get(':nth-child(10) > .offer-color > img').click()
        cy.get(':nth-child(11) > .offer-color > img').click()
        cy.get(':nth-child(12) > .offer-color > img').click()
        cy.get(':nth-child(13) > .offer-color > img').click()
        cy.get(':nth-child(14) > .offer-color > img').click()
        cy.get(':nth-child(15) > .offer-color > img').click()
        cy.get(':nth-child(16) > .offer-color > img').click()
        cy.get(':nth-child(17) > .offer-color > img').click()
        cy.get(':nth-child(18) > .offer-color > img').click()
        cy.get('#amount-mb')
        .type(100)
        cy.contains("a","Dodaj").click()
        cy.contains("a","Przejdź do koszyka").click()
        cy.contains("a","Przejdź do kasy").click()
        cy.contains("a","Kontynuuj").click()
        cy.get('#inputName')
            .type('test test')
        cy.get('#inputEmail')
        .type('test@email.com')
        cy.get('#inputAddress1')
        .type('58-570')
        cy.get('#inputAddress2')
        .type('Jelenia Góra')
        cy.get('#inputAddress3')
        .type('testowa')
        cy.get('#inputAddress4')
        .type(1)
        cy.get('#inputAddress5')
        .type(1)
        cy.get('#inputPhone')
        .type(12346789)
            cy.contains('Akceptuję').click()
            cy.contains("a","Przejdź").click()
            cy.contains("a","Zapłać").click()
        
    })
})