describe('test05', () => {
    it('Szukanie produktów + zapytanie', () => {
        cy.visit('https://artmeb-hurt.pl/')
        cy.get('#name-input')
            .type('Jungle')
        cy.contains("div>ul>li","Jungle").click()
        cy.contains(".link-more","Sprawdź").click()
        cy.contains("h5","Jungle").click()
        cy.contains("#ask-button > .link-more","Zapytaj").click()
        cy.get('#clientName')
            .type('test test')
        cy.get('#clientEmail')
            .type('test@email.com')
        cy.get('#clientPhone')
            .type(123456789)
        cy.get('#question')
            .type('Testowe zapytanie o produkt')
        cy.contains(":nth-child(1) > .custom-control-label","Potwierdzam").click()
        cy.contains(":nth-child(2) > .custom-control-label","Wyrażam zgodę").click()
        cy.contains("#send-form-product-question","Wyślij").click()
    })
})