describe('test01', () => {
    it('Sprawdzanie produktów według ceny', () => {
      cy.visit('https://artmeb-hurt.pl/')  // wejście na stronę https://artmeb-hurt.pl/
      cy.contains('Sklep').click()  // wejście do zakładki sklep
      cy.url().should('include', '/sklep')  // sprawdzenie ścieżki
      // element #amount2 - cena = 18
      cy.get('#amount1')  // cena min
        .clear()  // wyczyszczenie wartości
        .type(18) // ustawienie wartości
        .should('value', '18')  // sprawdzenie poprawności wartości      
      cy.get('#amount2')  //cena max
        .clear()  // wyczyszczenie wartości
        .type(18) // ustawienie wartości
        .should('value', '18')  // sprawdzenie poprawności wartości
      cy.contains('Sprawdź').click()  // wyszukanie produktów
      cy.url().should('include', '/sklep?&priceMin=18&priceMax=18')  // sprawdzenie ścieżki
      cy.contains('Malmo')  // sprawdzenie czy dany element znajduje się na stronie
      cy.contains('Sawana') // sprawdzenie czy dany element znajduje się na stronie

      // element #amount2 - cena = 19
      cy.get('#amount1')
        .clear()
        .type(19)
        .should('value', '19')      
      cy.get('#amount2')
        .clear()
        .type(19)
        .should('value', '19')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=19&priceMax=19') 
      cy.contains('Stark')

      // element #amount2 - cena = 20  
      cy.get('#amount1')
        .clear()
        .type(20)
        .should('value', '20')         
      cy.get('#amount2')
        .clear()
        .type(20)
        .should('value', '20')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=20&priceMax=20') 
      cy.contains('Alina PIK')
      
      // element #amount2 - cena = 21
      cy.get('#amount1')
        .clear()
        .type(21)
        .should('value', '21')      
      cy.get('#amount2')
        .clear()
        .type(21)
        .should('value', '21')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=21&priceMax=21')
      cy.contains('Denver')
      cy.contains('Inari')
      cy.contains('Kronos')
      cy.contains('Look')
      cy.contains('Rino')

      // element #amount2 - cena = 22     
      cy.get('#amount1')
        .clear()
        .type(22)
        .should('value', '22')      
      cy.get('#amount2')
        .clear()
        .type(22)
        .should('value', '22')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=22&priceMax=22')
      cy.contains('Avis')
      cy.contains('Cosmic')

      // element #amount2 - cena = 23 
      cy.get('#amount1')
        .clear()
        .type(23)
        .should('value', '23')         
      cy.get('#amount2')
        .clear()
        .type(23)
        .should('value', '23')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=23&priceMax=23')
      cy.contains('Cashmere')
      cy.contains('Evolution')
      cy.contains('Forever')
      cy.contains('Zetta')

      // element #amount2 - cena = 24
      cy.get('#amount1')
        .clear()
        .type(24)
        .should('value', '24')         
      cy.get('#amount2')
        .clear()
        .type(24)
        .should('value', '24')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=24&priceMax=24')
      cy.contains('Amor Velvet')
      cy.contains('Chester')
      cy.contains('Jasmine')
      cy.contains('Mono')
      cy.contains('Opera')
      cy.contains('Queens')
      cy.contains('Riviera')
      cy.contains('Royal Velvet')
      cy.contains('Salva')
      cy.contains('Victoria')

      // element #amount2 - cena = 25
      cy.get('#amount1')
        .clear()
        .type(25)
        .should('value', '25')         
      cy.get('#amount2')
        .clear()
        .type(25)
        .should('value', '25')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=25&priceMax=25')
      cy.contains('Amore')
      cy.contains('Kenya')
      cy.contains('Milo')
      cy.contains('Monolith')
      cy.contains('Nela')
      cy.contains('Primo D')
      cy.contains('Rango')

      // element #amount2 - cena = 26
      cy.get('#amount1')
        .clear()
        .type(26)
        .should('value', '26')         
      cy.get('#amount2')
        .clear()
        .type(26)
        .should('value', '26')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=26&priceMax=26')
      cy.contains('Alina')
      cy.contains('Avra')
      cy.contains('Brego')
      cy.contains('Cuba')
      cy.contains('Heritage')
      cy.contains('Megan')
      cy.contains('Vardo')
      cy.contains('Vasco')

      // element #amount2 - cena = 27
      cy.get('#amount1')
        .clear()
        .type(27)
        .should('value', '27')         
      cy.get('#amount2')
        .clear()
        .type(27)
        .should('value', '27')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=27&priceMax=27')
      cy.contains('Arne')
      cy.contains('Boss PIK')
      cy.contains('Cortes')
      cy.contains('Element')
      cy.contains('Milos')
      cy.contains('Preston')
      cy.contains('Ranger')
      cy.contains('Raquel')
      cy.contains('Solid')
      cy.contains('Solo')
      cy.contains('Ultra')

      // element #amount2 - cena = 28
      cy.get('#amount1')
        .clear()
        .type(28)
        .should('value', '28')         
      cy.get('#amount2')
        .clear()
        .type(28)
        .should('value', '28')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=28&priceMax=28')
      cy.contains('Aston')
      cy.contains('Austin')
      cy.contains('Fantasy Velvet')
      cy.contains('Matt Velvet')
      cy.contains('Norn')
      cy.contains('Palladium')
      cy.contains('Primo EM')

      // element #amount2 - cena = 29
      cy.get('#amount1')
        .clear()
        .type(29)
        .should('value', '29')         
      cy.get('#amount2')
        .clear()
        .type(29)
        .should('value', '29')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=29&priceMax=29')
      cy.contains('Alaska')
      cy.contains('Antonio')
      cy.contains('Brooklyn')
      cy.contains('Fuego')
      cy.contains('Harmony')
      cy.contains('Lecco')
      cy.contains('Liverpool')
      cy.contains('Magnum')
      cy.contains('Sally')
      cy.contains('Serta')
      cy.contains('Tiffany')
      cy.contains('Tula')
      cy.contains('Vogue')
      cy.contains('Watusi')

      // element #amount2 - cena = 30
      cy.get('#amount1')
        .clear()
        .type(30)
        .should('value', '30')         
      cy.get('#amount2')
        .clear()
        .type(30)
        .should('value', '30')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=30&priceMax=30')
      cy.contains('Amazon')
      cy.contains('Apollo')
      cy.contains('Ariko')
      cy.contains('Liwale')
      cy.contains('Luna')
      cy.contains('Palacio')
      cy.contains('Petra')     

      // element #amount2 - cena = 31
      cy.get('#amount1')
        .clear()
        .type(31)
        .should('value', '31')         
      cy.get('#amount2')
        .clear()
        .type(31)
        .should('value', '31')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=31&priceMax=31')
      cy.contains('Amor Velvet PIK')
      cy.contains('Arya')
      cy.contains('Bangkok')
      cy.contains('Camelia')
      cy.contains('Germes')
      cy.contains('Glitz')
      cy.contains('New Palermo')
      cy.contains('Paris')
      cy.contains('Tesla B')  

      // element #amount2 - cena = 32
      cy.get('#amount1')
        .clear()
        .type(32)
        .should('value', '32')         
      cy.get('#amount2')
        .clear()
        .type(32)
        .should('value', '32')
      cy.contains('Sprawdź').click()
      cy.url().should('include', '/sklep?&priceMin=32&priceMax=32')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')      

      // // element #amount2 - cena = 27
      // cy.get('#amount1')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')         
      // cy.get('#amount2')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')
      // cy.contains('Sprawdź').click()
      // cy.url().should('include', '/sklep?&priceMin=27&priceMax=27')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')

      // // element #amount2 - cena = 27
      // cy.get('#amount1')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')         
      // cy.get('#amount2')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')
      // cy.contains('Sprawdź').click()
      // cy.url().should('include', '/sklep?&priceMin=27&priceMax=27')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')

      // // element #amount2 - cena = 27
      // cy.get('#amount1')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')         
      // cy.get('#amount2')
      //   .clear()
      //   .type(27)
      //   .should('value', '27')
      // cy.contains('Sprawdź').click()
      // cy.url().should('include', '/sklep?&priceMin=27&priceMax=27')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')
      // cy.contains('')






      
    })
  })