describe('test07', () => {
    it('Cypress.io', () => {
        cy.visit('https://dashboard.cypress.io/login')
        cy.contains("Log in with Email").click( {force: true} )
        cy.get('#email')
            .type('test@email.com')
        cy.get('#password')
            .type('12345678')
        cy.contains(".btn-primary","Log In").click()
        cy.contains("Cancel").click()
        cy.contains("Sign up").click()
        cy.contains("Sign up with Email").click()      
        cy.get('#email')
            .type("test@email.com")
        cy.get('.ReactPasswordStrength-input')
            .type(1235678)
            .clear()
            .type(1234567890)
            .clear()
            .type("ZAQ!2wsx")
        cy.contains(".btn-primary","Sign Up").click()
        cy.get('#email')
            .clear()
            .type("test2@email.com")        
        cy.contains(".btn-primary","Sign Up").click()
        cy.contains('Log in').click()
        cy.get('#email')
            .type('test2@email.com')
        cy.get('#password')
            .type('ZAQ!2wsx')    
        cy.contains(".btn-primary","Log In").click()  
        // weryfikacja na podanym e-mail'u          
    })
})
