Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })
describe("test06", () => {
    it("Symulacja zakupu", () => {{
        cy.visit("https://artmeb-hurt.pl/")
        cy.contains("a.nav-link","Sklep").click()
        cy.wait(100)
        cy.get('#amount1')
            .clear()
            .type(30)        
        cy.get('#amount2')
            .clear()
            .type(40)
        cy.contains('Sprawdź').click()
        cy.get(':nth-child(1) > .content > .content-header > .title > h4').click()
        cy.get('#name-input')
            .type('Amazon')
        cy.contains('Sprawdź').click()        
        cy.contains("a","Amazon").click()
        cy.get('#amount-mb')
            .type(100)
        cy.contains("a","Dodaj").click()
        cy.contains("a","Przejdź do koszyka").click()
       // Konsola (F12): Uncaught TypeError: that.removeClass is not a function at scripts.js:521:18
       // Cypress: (uncaught exception) TypeError: that.removeClass is not a function
       cy.contains("a","Przejdź do kasy").click()
       cy.contains("a","Kontynuuj").click()
       cy.get('#inputName')
        .type('test test').should('have.value', 'test test')
       cy.get('#inputEmail')
       .type('test@email.com').should('have.value','test@email.com')
       cy.get('#inputAddress1')
       .type('58-570').should('have.value','58-570')
       cy.get('#inputAddress2')
       .type('Jelenia Góra').should('have.value','Jelenia Góra')
       cy.get('#inputAddress3')
       .type('testowa').should('have.value','testowa')
       cy.get('#inputAddress4')
       .type(1).should('have.value','1')
       cy.get('#inputAddress5')
       .type(1).should('have.value','1')
       cy.get('#inputPhone')
       .type(123456789).should('have.value','123456789')
        cy.contains('Akceptuję').click()
        cy.get('.form-trigger > .custom-control-label').click()
        cy.get('#fv-inputName')
        .type('test test').should('have.value','test test') 
        cy.get('#fv-inputCompany')    
        .type('test').should('have.value','test')   
        cy.get('#fv-inputNip')     
        .type('123-456-78-19').should('have.value','123-456-78-19')
        cy.get('#fv-inputEmail')
        .type('test@email.com').should('have.value','test@email.com')  
       cy.get('#fv-inputAddress1')
       .type('58-570').should('have.value','58-570')
       cy.get('#fv-inputAddress2')
       .type('Jelenia Góra').should('have.value','Jelenia Góra')
       cy.get('#fv-inputAddress3')
       .type('testowa').should('have.value','testowa')
       cy.get('#fv-inputAddress4')
       .type(1).should('have.value','1')
       cy.get('#fv-inputAddress5')
       .type(1).should('have.value','1')
       cy.get('#fv-inputPhone')
       .type(123456789).should('have.value','123456789')                     
        cy.contains("a","Przejdź").click()
        cy.contains("a","Zapłać").click()
        // Płatność za zakup za pośrednictwem strony: secure.payu.com
    }})
})